name: Release

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
      NUGET_REPO_URL: nuget.org
      NUGET_REPO_KEY: ${{ secrets.NUGET_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore tools
      run: dotnet tool restore
    - name: Build
      run: dotnet fsi build.fsx -t release
